import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Button, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { alterarStatusGuarda, cadastrarGuarda, listarGuardas, type Usuario } from "../src/services/auth";
import { useApp } from "../src/context/AppContext";

export default function AdminScreen(): React.ReactElement {
  const router = useRouter(); const { perfil, entrarComoAdmin, sair } = useApp();
  const [carregando, setCarregando] = useState(false); const [email, setEmail] = useState(""); const [senha, setSenha] = useState("");
  const [guardas, setGuardas] = useState<Usuario[]>([]); const [form, setForm] = useState({ nome: "", matricula: "", pin: "" });
  const carregar = async (): Promise<void> => { setCarregando(true); try { setGuardas(await listarGuardas()); } catch { Alert.alert("Erro", "Não foi possível listar os guardas."); } finally { setCarregando(false); } };
  useEffect(() => { if (perfil === "admin") void carregar(); }, [perfil]);
  const login = async (): Promise<void> => { setCarregando(true); try { await entrarComoAdmin(email, senha); setSenha(""); } catch (error) { Alert.alert("Acesso negado", error instanceof Error ? error.message : "Credenciais inválidas."); } finally { setCarregando(false); } };
  const cadastrar = async (): Promise<void> => { setCarregando(true); try { const guarda = await cadastrarGuarda(form.nome, form.matricula, form.pin); setGuardas((atuais) => [...atuais, guarda].sort((a, b) => a.nome.localeCompare(b.nome))); setForm({ nome: "", matricula: "", pin: "" }); Alert.alert("Guarda cadastrado", `${guarda.nome} já pode entrar.`); } catch (error) { Alert.alert("Cadastro não realizado", error instanceof Error ? error.message : "Verifique os dados."); } finally { setCarregando(false); } };
  const alternar = async (guarda: Usuario): Promise<void> => { try { const atualizado = await alterarStatusGuarda(guarda, !guarda.ativo); setGuardas((atuais) => atuais.map((item) => item.uid === atualizado.uid ? atualizado : item)); } catch { Alert.alert("Erro", "Não foi possível alterar o status."); } };

  if (perfil !== "admin") return <View style={styles.page}><View style={styles.card}><Text style={styles.title}>Administração</Text><Text style={styles.subtitle}>Acesso exclusivo do administrador.</Text><TextInput style={styles.input} placeholder="E-mail administrativo" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" /><TextInput style={styles.input} placeholder="Senha" value={senha} onChangeText={setSenha} secureTextEntry onSubmitEditing={() => void login()} /><Button title={carregando ? "Entrando..." : "Entrar"} onPress={() => void login()} disabled={carregando} /><Pressable onPress={() => router.replace("/identificacao")}><Text style={styles.link}>Voltar ao acesso do guarda</Text></Pressable></View></View>;

  return <View style={styles.page}><View style={styles.header}><View><Text style={styles.title}>Guardas cadastrados</Text><Text style={styles.subtitle}>{guardas.length} registro(s)</Text></View><Button title="Sair" onPress={() => void sair()} /></View><View style={styles.card}><Text style={styles.sectionTitle}>Cadastrar novo guarda</Text><TextInput style={styles.input} placeholder="Nome completo" value={form.nome} onChangeText={(nome) => setForm({ ...form, nome })} /><TextInput style={styles.input} placeholder="Matrícula" value={form.matricula} onChangeText={(matricula) => setForm({ ...form, matricula })} autoCapitalize="none" /><TextInput style={styles.input} placeholder="PIN de 6 dígitos" value={form.pin} onChangeText={(pin) => setForm({ ...form, pin: pin.replace(/\D/g, "") })} keyboardType="number-pad" secureTextEntry maxLength={6} /><Button title="Cadastrar guarda" onPress={() => void cadastrar()} disabled={carregando} /></View>{carregando ? <ActivityIndicator size="large" /> : <FlatList data={guardas} keyExtractor={(item) => item.uid} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={styles.guardCard}><View style={styles.guardInfo}><Text style={styles.guardName}>{item.nome}</Text><Text>Matrícula: {item.matricula}</Text><Text style={item.ativo ? styles.active : styles.inactive}>{item.ativo ? "Ativo" : "Inativo"}</Text></View><Button title={item.ativo ? "Bloquear" : "Reativar"} color={item.ativo ? "#dc2626" : "#16a34a"} onPress={() => void alternar(item)} /></View>} ListEmptyComponent={<Text style={styles.empty}>Nenhum guarda cadastrado.</Text>} />}</View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#f1f5f9", padding: 20, gap: 16 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, card: { backgroundColor: "#fff", borderRadius: 14, padding: 20, gap: 12, width: "100%", maxWidth: 720, alignSelf: "center" }, title: { fontSize: 26, fontWeight: "700" }, subtitle: { color: "#475569" }, sectionTitle: { fontSize: 18, fontWeight: "700" }, input: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 9, padding: 12, backgroundColor: "#fff" }, link: { color: "#2563eb", textAlign: "center", padding: 8 }, list: { gap: 10, width: "100%", maxWidth: 720, alignSelf: "center" }, guardCard: { backgroundColor: "#fff", borderRadius: 12, padding: 16, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, guardInfo: { flex: 1, gap: 3 }, guardName: { fontSize: 17, fontWeight: "700" }, active: { color: "#15803d", fontWeight: "700" }, inactive: { color: "#b91c1c", fontWeight: "700" }, empty: { textAlign: "center", color: "#64748b", padding: 24 } });
